// ============================================================
// Base Type Questions - Expanded (40 questions, 10 per dimension)
// ============================================================

import { BaseTypeQuestion } from "./diagnosticData";

export const BASE_TYPE_QUESTIONS_EXPANDED: BaseTypeQuestion[] = [
  // E/I (10 questions)
  { id:"bt1", dimension:"EI", text:"新しいプロジェクトに取り組むとき、あなたはどちらに近いですか？",
    optionA:{label:"チームで議論しながらアイデアを出す",pole:"E"},
    optionB:{label:"一人で深く考えてから共有する",pole:"I"} },
  { id:"bt2", dimension:"EI", text:"エネルギーが充電されるのはどんなときですか？",
    optionA:{label:"人と活発に交流した後",pole:"E"},
    optionB:{label:"静かに一人で過ごした後",pole:"I"} },
  { id:"bt3", dimension:"EI", text:"問題解決のアプローチとして好むのは？",
    optionA:{label:"他者と対話しながら解決策を探る",pole:"E"},
    optionB:{label:"内省し、自分の中で答えを見つける",pole:"I"} },
  { id:"bt4", dimension:"EI", text:"会議やミーティングでのあなたの傾向は？",
    optionA:{label:"積極的に発言し、議論をリードする",pole:"E"},
    optionB:{label:"じっくり聞いてから、厳選した意見を述べる",pole:"I"} },
  { id:"bt5", dimension:"EI", text:"週末の理想的な過ごし方は？",
    optionA:{label:"友人や仲間と活動的に過ごす",pole:"E"},
    optionB:{label:"読書や趣味など、自分のペースで過ごす",pole:"I"} },
  { id:"bt5b", dimension:"EI", text:"ストレスを感じたとき、あなたは？",
    optionA:{label:"友人に話を聞いてもらい、気分転換する",pole:"E"},
    optionB:{label:"一人の時間を作り、落ち着きを取り戻す",pole:"I"} },
  { id:"bt5c", dimension:"EI", text:"学習や成長の機会として最も惹かれるのは？",
    optionA:{label:"ワークショップやセミナーなど、人と学ぶ環境",pole:"E"},
    optionB:{label:"書籍やオンライン講座など、自分のペースで学ぶ",pole:"I"} },
  { id:"bt5d", dimension:"EI", text:"人間関係の構築について、あなたは？",
    optionA:{label:"多くの人と浅く広く関係を築くのが得意",pole:"E"},
    optionB:{label:"少数の人と深く関係を築くのが得意",pole:"I"} },
  { id:"bt5e", dimension:"EI", text:"アイデアが浮かぶのは？",
    optionA:{label:"他者との会話や外部刺激を受けているとき",pole:"E"},
    optionB:{label:"一人で考えたり、瞑想しているとき",pole:"I"} },
  { id:"bt5f", dimension:"EI", text:"キャリアの理想像として近いのは？",
    optionA:{label:"多くの人と関わり、ネットワークを広げる仕事",pole:"E"},
    optionB:{label:"専門性を深め、個人の影響力を高める仕事",pole:"I"} },

  // S/N (10 questions)
  { id:"bt6", dimension:"SN", text:"情報を処理するとき、あなたが重視するのは？",
    optionA:{label:"具体的な事実やデータ",pole:"S"},
    optionB:{label:"全体的なパターンや可能性",pole:"N"} },
  { id:"bt7", dimension:"SN", text:"仕事で最も信頼するのは？",
    optionA:{label:"過去の実績と検証済みの方法",pole:"S"},
    optionB:{label:"直感とまだ試されていないアイデア",pole:"N"} },
  { id:"bt8", dimension:"SN", text:"説明を受けるとき、どちらが理解しやすいですか？",
    optionA:{label:"具体的な例やステップバイステップの手順",pole:"S"},
    optionB:{label:"概念的な枠組みや全体像",pole:"N"} },
  { id:"bt9", dimension:"SN", text:"新しいスキルを学ぶとき、あなたは？",
    optionA:{label:"まず実践して体で覚える",pole:"S"},
    optionB:{label:"まず理論を理解してから取り組む",pole:"N"} },
  { id:"bt10", dimension:"SN", text:"計画を立てるとき、あなたが注目するのは？",
    optionA:{label:"現実的な制約と実行可能性",pole:"S"},
    optionB:{label:"理想的なビジョンと革新的な可能性",pole:"N"} },
  { id:"bt10b", dimension:"SN", text:"ニュースや情報を読むとき、あなたは？",
    optionA:{label:"事実や数字などの具体的な情報に注目する",pole:"S"},
    optionB:{label:"その背景にある意味や今後の影響を考える",pole:"N"} },
  { id:"bt10c", dimension:"SN", text:"問題が複雑になったとき、あなたは？",
    optionA:{label:"細部を丁寧に分解し、ステップバイステップで解く",pole:"S"},
    optionB:{label:"全体像を把握し、本質的な解決策を見つける",pole:"N"} },
  { id:"bt10d", dimension:"SN", text:"他者の話を聞くとき、あなたは？",
    optionA:{label:"具体的な事実や詳細を確認する",pole:"S"},
    optionB:{label:"その背景にある意図や感情を読み取る",pole:"N"} },
  { id:"bt10e", dimension:"SN", text:"創造的な仕事において、あなたは？",
    optionA:{label:"既存の要素を組み合わせ、改善する",pole:"S"},
    optionB:{label:"まったく新しい概念や枠組みを創造する",pole:"N"} },
  { id:"bt10f", dimension:"SN", text:"リスク評価をするとき、あなたは？",
    optionA:{label:"過去のデータや統計に基づいて判断する",pole:"S"},
    optionB:{label:"直感や将来のシナリオに基づいて判断する",pole:"N"} },

  // T/F (10 questions)
  { id:"bt11", dimension:"TF", text:"重要な決断を下すとき、最も重視するのは？",
    optionA:{label:"論理的な分析と客観的な基準",pole:"T"},
    optionB:{label:"関係者の感情と価値観への影響",pole:"F"} },
  { id:"bt12", dimension:"TF", text:"フィードバックを与えるとき、あなたは？",
    optionA:{label:"率直に改善点を指摘する",pole:"T"},
    optionB:{label:"相手の気持ちに配慮しながら伝える",pole:"F"} },
  { id:"bt13", dimension:"TF", text:"チーム内で意見が対立したとき、あなたは？",
    optionA:{label:"最も論理的に正しい意見を支持する",pole:"T"},
    optionB:{label:"全員が納得できる落としどころを探す",pole:"F"} },
  { id:"bt14", dimension:"TF", text:"成功の定義として、あなたに近いのは？",
    optionA:{label:"目標を効率的に達成すること",pole:"T"},
    optionB:{label:"関わる人々が満足し成長すること",pole:"F"} },
  { id:"bt15", dimension:"TF", text:"問題が発生したとき、最初に考えるのは？",
    optionA:{label:"原因を特定し、再発防止策を立てる",pole:"T"},
    optionB:{label:"影響を受けた人のケアを優先する",pole:"F"} },
  { id:"bt15b", dimension:"TF", text:"他者の失敗に対して、あなたは？",
    optionA:{label:"何が間違っていたのか、冷静に分析する",pole:"T"},
    optionB:{label:"相手の気持ちを理解し、励ましやサポートを優先する",pole:"F"} },
  { id:"bt15c", dimension:"TF", text:"組織の方針が個人の価値観と対立したとき、あなたは？",
    optionA:{label:"ルールに従い、感情は脇に置く",pole:"T"},
    optionB:{label:"自分の価値観を大切にし、異議を唱える",pole:"F"} },
  { id:"bt15d", dimension:"TF", text:"報酬や昇進の基準として、あなたが重視するのは？",
    optionA:{label:"成果や効率性などの客観的な指標",pole:"T"},
    optionB:{label:"貢献度や人間関係など、主観的な評価",pole:"F"} },
  { id:"bt15e", dimension:"TF", text:"困っている人を見たとき、あなたは？",
    optionA:{label:"実際的なアドバイスや解決策を提供する",pole:"T"},
    optionB:{label:"まず相手の気持ちに共感し、寄り添う",pole:"F"} },
  { id:"bt15f", dimension:"TF", text:"職場の人間関係について、あなたは？",
    optionA:{label:"仕事の関係として、適切な距離を保つ",pole:"T"},
    optionB:{label:"友人のような深い関係を築きたい",pole:"F"} },

  // J/P (10 questions)
  { id:"bt16", dimension:"JP", text:"仕事の進め方として好むのは？",
    optionA:{label:"計画を立て、スケジュール通りに進める",pole:"J"},
    optionB:{label:"状況に応じて柔軟に対応する",pole:"P"} },
  { id:"bt17", dimension:"JP", text:"締め切りに対するあなたの態度は？",
    optionA:{label:"余裕を持って早めに完了させたい",pole:"J"},
    optionB:{label:"締め切り直前に集中力が最大化する",pole:"P"} },
  { id:"bt18", dimension:"JP", text:"旅行の計画を立てるとき、あなたは？",
    optionA:{label:"詳細なスケジュールを事前に決める",pole:"J"},
    optionB:{label:"大まかな方向だけ決めて、現地で判断する",pole:"P"} },
  { id:"bt19", dimension:"JP", text:"新しい情報が入ったとき、あなたは？",
    optionA:{label:"既存の計画に組み込み、決断を確定させる",pole:"J"},
    optionB:{label:"選択肢を開いたまま、さらに情報を集める",pole:"P"} },
  { id:"bt20", dimension:"JP", text:"デスクや作業環境について、あなたは？",
    optionA:{label:"整理整頓され、すべてが定位置にある",pole:"J"},
    optionB:{label:"一見散らかっているが、自分なりの秩序がある",pole:"P"} },
  { id:"bt20b", dimension:"JP", text:"プロジェクト管理において、あなたは？",
    optionA:{label:"マイルストーンを明確に設定し、進捗を厳密に追跡する",pole:"J"},
    optionB:{label:"大まかなゴールを設定し、途中で調整する",pole:"P"} },
  { id:"bt20c", dimension:"JP", text:"決断を下すとき、あなたは？",
    optionA:{label:"十分に検討してから、確定的に決める",pole:"J"},
    optionB:{label:"ある程度の情報で判断し、後で修正する",pole:"P"} },
  { id:"bt20d", dimension:"JP", text:"ルールや規則に対して、あなたは？",
    optionA:{label:"ルールは守るべき重要なものと考える",pole:"J"},
    optionB:{label:"状況に応じて、柔軟に解釈すべきと考える",pole:"P"} },
  { id:"bt20e", dimension:"JP", text:"目標達成のプロセスについて、あなたは？",
    optionA:{label:"計画通りに進めることが重要",pole:"J"},
    optionB:{label:"結果が出れば、プロセスは柔軟でいい",pole:"P"} },
  { id:"bt20f", dimension:"JP", text:"変化や予期しない出来事に対して、あなたは？",
    optionA:{label:"計画を修正し、新しい秩序を作る",pole:"J"},
    optionB:{label:"その場で対応し、流れに身を任せる",pole:"P"} },
];
